version: '3.4'

services:
  exercise.wwwapi:
    image: ${DOCKER_REGISTRY-}exercisewwwapi
    build:
      context: .
      dockerfile: exercise.wwwapi/Dockerfile
    ports: 
      - "7000:7000"
      - "7001:7001"

  exercise.database:
    image: postgres:latest
    container_name: exercise.database
    environment:
     - POSTGRES_DB=exercises
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/exercise-db:/var/lib/postgresql/data
    ports:
      - 5432:5432